
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
#  mode: yaml
  resources:
    - url: /local/style.css
      type: css

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Portainer i HA
panel_iframe:
  portainer:
    title: "Portainer"
    url: "http://192.168.10.34:9000/#/containers"
    icon: mdi:docker
    require_admin: true

panel_iframe:
  node_red:
    title: "Node Red"
    icon: mdi:nodejs
    url: "http://192.168.10.34:1880"
